name: tests

on:
  push:
    branches: [ master, 'release/0.3' ]
  pull_request:
    branches: [ master, 'release/0.3' ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: [ubuntu-latest, windows-latest, macos-latest]
            regex: [latest]
            include:
              - os: ubuntu-latest
                regex: '1.7.1'
    steps:
    - uses: actions/checkout@v7
    - name: Select minimum regex version
      if: matrix.regex != 'latest'
      run: cargo update -p regex --precise "${{ matrix.regex }}"
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
